### ISSUE TITLE
[Suggestion] Make acquiring gold ingots early game easier

### ISSUE THREAD

**Issue by zhguyu** [jsorrell/skyblock#16]
Drowned dropping copper in 1.17 does have a huge influence on how early progression works in skyblock. Although I do like the idea of crafting blast furnace using prismarine, it is still a great pain to get the gold ingots to cure villagers. 16 ingots translate to 144 nuggets, and getting 144 gold equipments from mob farm with a bare wooden sword is just not how it should work. We have already spent hours in the mob farm for 10 iron ingots, and that should be the end of this stage of the game. Still, the way to solve this is rather simple: make blasting gold items produce ingots instead of nuggets, or change the recipe of golden apples to use nuggets just like in the good old days (not preferred since zombified piglin farm later would produce a lot of nuggets). Farming for 16 gold items is reasonable before we can leave the mob farm for good.

**Comment by Anonym271** [comment]
There actually is a way to get gold in the overworld, and it is again involving drowneds: get some copper to build a lightning rod, build a pig farm and then place a lightning rod between your pigs (you need about 300 of them). Then just wait until a lightning strikes your pigs (let it run overnight) and they will be converted into zombified piglins that you can kill to get gold nuggets and occasionally even ingots. And since it is not advisable to build a lightning based farm out of would this way even encourages players to build a prismarine farm.
I tried this out in my skyblock world and it works like a charm - you can even build some kind of semi-automatic farm out of it. And it is completely vanilla and not even that grindy.
So technically the blast furnace recipe would not even be necessary.

**Comment by zhguyu** [comment]
This sounds quite promising actually, especially since you said you've implemented it in your own playthrough. I don't know how much efforts do we need to get 300 pigs though, and how long we have to wait before a pair of pigs spawn on the grass.

In the mean time, I'd like to remind that we do have a (somehow) fireproof material in early game: netherrack, which can be crafted out of rotten flesh. This is a recipe added in the skyblock datapack. Zombified piglins are immune to fire so it should be fine. Thus building a prismarine farm is not needed.

By the way, I do realise in my own playthrough that a minor flaw is introduced by the blast furnace recipe: it allows players to recruit armourer villagers before getting lava from a wandering trader. It's not a big deal at all - but it's tempting.

**Comment by Anonym271** [comment]
You are right, I forgot about that netherrack recipe because I removed it from my playthrough and added it into the piglin bartering loot table instead.

Getting a pair of pigs to spawn works quite fast in my experience as soon as you are at Y0. And breeding them can be made (semi-)automatic by having the player in a water stream floating past some pig pairs. If you place the pigs on open trap doors, the baby pigs will just fall through as soon as they spawn. Then you can collect them with a water stream under your farm and bring them to a central place with a lightning rod.

**Comment by jsorrell** [comment]
> There actually is a way to get gold in the overworld, and it is again involving drowneds: get some copper to build a lightning rod, build a pig farm and then place a lightning rod between your pigs (you need about 300 of them). Then just wait until a lightning strikes your pigs (let it run overnight) and they will be converted into zombified piglins that you can kill to get gold nuggets and occasionally even ingots. And since it is not advisable to build a lightning based farm out of wood this way even encourages players to build a prismarine farm. I tried this out in my skyblock world and it works like a charm - you can even build some kind of semi-automatic farm out of it. And it is completely vanilla and not even that grindy. So technically the blast furnace recipe would not even be necessary.

As of 1.3.1, this is now the intended (and only?) way to get the required gold.
